# Generated by Django 3.1.3 on 2021-01-06 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='imagedetail',
            name='image_thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
