# Generated by Django 3.1.3 on 2021-01-07 04:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0002_imagedetail_image_thumbnail'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='imagedetail',
            name='image_thumbnail',
        ),
    ]
