# Generated by Django 3.1.3 on 2021-01-11 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0004_imagedetail_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='imagedetail',
            name='download_mode',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
