# Generated by Django 3.1.3 on 2021-01-11 17:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0005_imagedetail_download_mode'),
    ]

    operations = [
        migrations.RenameField(
            model_name='imagedetail',
            old_name='download_mode',
            new_name='approval',
        ),
    ]
