# Generated by Django 3.1.3 on 2021-01-12 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0006_auto_20210111_2312'),
    ]

    operations = [
        migrations.AddField(
            model_name='imagedetail',
            name='description',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
